declare interface Language {
    // ERRORS
    errLoginPass: string;
    errLoginNotFound: string;
    errLoginUnverified: string;
    errResetNotFound: string;
    errResetToken: string;
    errDefault: string;
    errRegConflict: string;
    errBadRequest: string;
    errProfileLoginExp: string;
    errFileTooLarge: string;

    // WARNINGS
    warnOverload: string;
    warnDateLimit1: string;
    warnDateLimit2: string;
    
    // NAVBAR
    navReg: string;
    navLogin: string;
    navLocation: string;
    navGallery: string;
    navPrograms: string;
    navPrices: string;
    navAccom: string;
    navEventCenter: string;
    navGetting: string;
    navPoi: string;
    navLegal: string;
    navFaq: string;
    navParticipants: string;
    navStaff: string;
    navProfile: string;
    navEvent: string;
    navImportant: string;
    navTickets: string;
    navRooms: string;
    navAdmin: string;
    navLogout: string;
    navMe: string;
    navStatistics: string;

    // FOOTER
    footerHelp: string;
    footerLegal: string;
    footerPartners: string;
    footerOrli: string;
    footerFind: string;
    footerFaq: string;
    footerContact: string;
    footerData: string;
    footerRules: string;
    footerTos: string;
    footerOrliText: string;
    footerOrliText2: string;
    footerOrliText3: string;
    footerFacebook: string;
    footerTelegramChat: string;
    footerTelegramAnnounce: string;

    // INFOCARD
    infoCardButton: string;
    infoCardTime: string;

    // LEGAL
    legalTos: string;
    legalRules: string;
    legalData: string;

    // CONTACT
    contact: string;

    // GALLERY
    galleryVideos: string;
    galleryImages: string;

    // FAQ
    faqIntro: string;
    faqSearch: string;

    // HOME
    homeBtnReg: string;
    homeBtnGallery: string;
    homeBtnLocation: string;
    homeNext: string;
    homeLocation: string;
    homeTheme: string;
    homeThemeDesc1: string;
    homeThemeDesc2: string;
    homeAbout1: string;
    homeAbout2: string;
    homeText5: string;

    // LOCATION
    locMapOpen: string;
    locPOIOpen: string;
    locLocation: string;
    locZoom: string;
    locAddress: string;
    locDistance: string;
    locEventC1: string;
    locEventC20: string;
    locEventC21: string;
    locEventC22: string;
    locEventC23: string;
    locPoi: string;
    locPolicy: string;
    locFAQ: string;
    locAccom1: string;
    locAccom2: string;
    locAccom3: string
    locAccom31: string
    locAccom32: string
    locAccom4: string;
    locAccomT1: string;
    locAccomT1L1: string;
    locAccomT1L2: string;
    locAccomT1L3: string;
    locAccomT1L4: string;
    locAccomT2: string;
    locAccomT2L1: string;
    locAccomT2L2: string;
    locAccomT2L3: string;
    locAccomT2L4: string;
    locAccomT3: string;
    locAccomT3L1: string;
    locAccomT3L2: string;
    locAccomT3L3: string;
    locAccomT3L4: string;
    locAccomT4: string;
    locAccomT4L1: string;
    locAccomT4L2: string;
    locAccomT4L3: string;
    locAccomT4L4: string;
    locGetting1: string;
    locGetting1L1: string;
    locGetting1L2: string;
    locGetting2: string;
    locGetting2L1: string;
    locGetting2L2: string;
    locGetting3: string;
    locGetting3L1: string;
    locGetting3L2: string;
    locGetting4: string;
    locGetting4L1: string;
    locGetting4L2: string;
    locGetting5: string;
    locGetting5L1: string;
    locGetting5L2: string;
    locGetting5L3: string;

    // STAFF
    staffIntro: string;
    staffVolunteers: string;

    // INPUTS
    natSelectSelect: string;
    natSelectPlaceholder: string;

    // DATEPICKER
    dateFormat: string;
    dateClose: string;

    // REGISTRATION
    regFirstname: string;
    regLastname: string;
    regFursonaName: string;
    regEmail: string;
    regEmailConfirm: string;
    regPassword: string;
    regPasswordConfirm: string;
    regDob: string;
    regSpecies: string;
    regNationality: string;
    regButton: string;
    regSearchablePlaceholder: string;
    regPleaseSelect: string;
    regRule1: string;
    regRule2: string;
    regRuleBtn: string;
    regData1: string;
    regDataBtn: string;
    regContact: string;
    regContactExp: string;
    regAllergy: string;

    // REGISTRATION MESSAGES
    regWait: string;
    regFirstNameError: string;
    regLastNameError: string;
    regEmailError: string;
    regEmailConfError: string;
    regSonaNameError: string;
    regSonaSpeciesError: string;
    regDateError: string;
    regUnderAgeError: string;
    regInvalidAgeError: string;
    regNationalityError: string;
    regPassError: string;
    regPassConfError: string;
    regContactErr: string;

    // REGISTRATION SUCCESS
    regSuccessTitle: string;
    regSuccessWelcome: string;
    regSuccessDesc1: string;
    regSuccessDesc2: string;
    regSuccessOutro: string;
    regSuccessButton: string;

    // PARTICIPANTS
    partNationality: string;
    partCounterAll: string;
    partCounterSuit: string;
    partSuiter: string;
    partSponsor: string;

    // LOGIN
    loginRemember: string;
    loginWait: string;
    loginEmailError: string;
    loginPassError: string;
    loginForgotPass: string;
    loginButton: string;

    // RESET
    resetTitle: string;
    resetInstruct1: string;
    resetInstruct2: string;
    resetButton: string;
    resetButtonToken: string;
    resetPass: string;
    resetPassConf: string;

    // RESET MESSAGES
    resetEmailSent: string;
    resetSuccess: string;

    // PROFILE
    ProfWait: string;
    profSuccess: string;
    profPicture: string;
    profOverview: string;
    profData: string;
    profUnsupportedType: string;
    profCancel: string;
    profConfirm: string;
    profImageUpload: string;
    profSuiter: string;
    profPassword: string;
    profSave: string;
    profPayment: string;
    profRoom: string;
    profProcessing: string;
    profNotPaid: string;
    profNotSelected: string;
    profPaid: string;
    profTicketDisabled: string;
    profSelected: string;
    profNotSelectable: string;
    profTicketNotVerified: string;
    profImageLimit1: string;
    profImageLimit2: string;

    // TICKETS
    ticketTickets: string;
    ticketTicket: string;
    ticketExtra: string;
    ticketSelect: string;
    ticketCancel: string;
    ticketDaySelect: string;
    ticketClear: string;
    ticketFoodSelect: string;
    ticketFood: string;
    ticketNoFood: string;
    ticketSponsor: string;
    ticketOverview: string;
    ticketSponsorQuestion: string;
    ticketSponsorText1: string;
    ticketSponsorText2: string;
    ticketSponsorAmount: string;
    ticketOverviewTicket: string;
    ticketNoTicket: string;
    ticketNoExtra: string;
    ticketDay: string;
    ticketDays: string;
    ticketNoDay: string;
    ticketNoDays: string;
    ticketSponsorLevel: string;
    ticketSuperSponsor: string;
    ticketPrice: string;
    ticketFinalPrice: string;
    ticketBuy: string;
    ticketPurchaseQuestion: string;
    ticketAlreadyHas: string;
    ticketEarlyBird: string;
    ticketEarlyBirdExp: string;
    ticketSuccess: string;
    ticketSponsorShirt: string;
    ticketNoShirt: string;
    ticketShirtSize: string;
    ticketNotAvailable: string;
    ticketNotAllowed0: string;
    ticketNotAllowed1: string;

    // PROGRAMS
    progList: string;

    // ROOM
    roomHouse: string;
    roomRoom: string;
    roomJoin: string;
    roomAdmin: string;
    roomClose: string;
    roomRegDate: string;
    roomTelegram: string;
    roomNoTelegram: string;
    roomPIN: string;
    roomOptional: string;
    roomCancel: string;
    roomLock: string;
    roomLockQuestion: string;
    roomLockQuestion2: string;
    roomCustom: string;
    roomCustomQuestion: string;
    roomTelegramQuestion: string;
    roomPINError: string;
    roomCustomNameError: string;
    roomTelegramError: string;
    roomBadPIN: string;
    roomErrConflict: string;
    roomLeave: string;
    roomLeaveAsk: string;
    roomIntro1: string;
    roomIntro2: string;
    roomIntroList: string[];

    // INFO



    // ADMIN
    paginationSize: string;
    paginationPage: string;
    paginationNumber: string;
    adminSearch: string;
    adminVerifiedChart: string;
    adminVerified: string;
    adminUnverified: string;
    adminPaidChart: string;
    adminPaid: string;
    adminNotPaid: string;
    adminView: string;
    adminAge: string;
    adminPaidTrue: string;
    adminPaidFalse: string;
    adminPaymentMethod: string;
    adminReset: string;
    adminNoData: string;
    adminTotal: string;
    adminRemovePic: string;
    adminSave: string;
    adminRevert: string;
    adminAsk: string;
    adminYes: string;
    adminNo: string;
    adminVerify: string;
    adminReject: string;
    adminPaymentConf: string;
    adminLimit: string;
    adminRemoveRoom: string;
    adminNavSearch: string;
    adminUser: string;
    adminRoomFalse: string;
    adminRoomTrue: string;
    adminRoomForce: string;
}